# -*- coding: utf-8 -*-
import xlsxwriter   # pip install xlsxwriter if needed
import argparse
import pandas as pd
from random import shuffle
import os
# 為了幫328seat, 326seat, 323seat三間教室的座位表，各複製一個sheet所需的Input
from openpyxl import Workbook 
from openpyxl import load_workbook 

"""
使用者可以自行修改的地方：
(1) adjust_name_list: 有些同學的名字在 member.xls 會是亂碼，請參照下面的格式將亂碼與對應的正確名字填上。
    E.g., adjust_name_list = [("謝&#21894;安", "謝喆安"), ("陳韋&#21234;", "陳韋勲")]
(2) max_seat: 各教室欲分配的人數 (328, 326, 323)，人數超出教室上限則以教室上限計之。
    E.g., max_seat = [45, 50, 23]
(3) seat328_invalid, seat326_invalid, seat323_invalid: 
    各教室不能使用的座位，兩個值分別是試算表上的 row、col (從 0 開始算)。
    E.g., seat328_invalid = [(1, 3), (6, 6), (7, 6)]
"""
adjust_name_list = []
max_seat = [40, 50, 23]     # [Note] : virus
seat328_invalid = []
seat326_invalid = []
seat323_invalid = []

parser = argparse.ArgumentParser()
parser.add_argument("--PASSWD_FILE_PATH",   default="./input/password.txt", help="the path to the (team, passwd) file generated by NTHU OJ")
parser.add_argument("--NAME_FILE_PATH",     default="./input/member.xlsx",   help="the path to the (student ID, Name) file downloaded from ILMS)")
parser.add_argument("--OUTPUT_PATH",        default="./output/seat.xlsx",   help="the path to output the result")
args = parser.parse_args()

"""
建立 account_list，即帳號與其對應密碼的清單。
E.g., [(123, 'AbCdEfG'), (124, 'aBcDeFg'), ...]
"""
account_list = []
file = open(args.PASSWD_FILE_PATH, 'r')
for line in file.readlines():
    elements = line.split(',')
    # 不處理檔案第一行和第二行的資訊
    if(elements[1].endswith("users\n") or elements[0].endswith("Username")):
        pass
    else:
        account = (int(elements[0][4:]), elements[1][:-1])
        account_list.append(account)
file.close()
# 將 account_list 按照 team number 由小到大排序
account_list = sorted(account_list, key = lambda x:x[0])
print("account num:", len(account_list))

"""
建立 name_list，即包含姓名、學號、系級 的清單。
E.g., [('楊舜仁', '123456789', '資工系'), ...]
"""
name_list = []
df = pd.read_excel(args.NAME_FILE_PATH)
for index, row in df.iterrows():
    if (index == 0): continue
    name = (row[1], row[0], row[3]) # row[1] == studentID, row[0] == name, row[3] == department
    print(name)
    # 將同學名字中的亂碼修正
    for adjust_name in adjust_name_list:
        if name[1] == adjust_name[0]:
            name = (row[1], adjust_name[1], row[3])
    name_list.append(name)

# 對 name_list 進行亂數
copy = name_list
shuffle(copy)
name_list = copy
# 記錄 name_list 的人數
name_list_num = len(name_list)
print("student num:", name_list_num)

"""
定義試算表以及各個 format。
"""
workbook = xlsxwriter.Workbook(args.OUTPUT_PATH)
format1 = workbook.add_format({'font_size':8,'valign':'top','border':2})                        # 帳號座位
format2 = workbook.add_format({'align':'center','valign':'vcenter','font_name':'consolas', \
                              'font_size':14,'border':2})                                       # 空的座位
format3 = workbook.add_format({'align':'center','valign':'vcenter','border':2, 'font_size':16}) # 名字座位
format4 = workbook.add_format({'diag_type':3,'border':2})                                       # 打叉的座位
format5 = workbook.add_format({'align':'center','valign':'vcenter', 'font_size':16})            # 講台

"""
變數名稱與試算表名稱的對應關係。
"""
# 變數名稱 ---- 試算表名稱
# worksheetTN   TEAM_NAME
# worksheetRT   TEAM_ACCOUNT    [Note] : virus
# seat328       328seat
# seat328 copy  328seat copy    
# signIn328     328signIn
# seat326       326seat
# seat326 copy  326seat copy    
# signIn326     326signIn
# seat323       323seat
# seat323 copy  323seat copy    
# signIn323     323signIn
# account328    328_Account
# account326    326_Account
# account323    323_Account
# backupAccount    backup_Account

"""
建立 TEAM_NAME，即學生與帳號的對應表。
"""
worksheetTN = workbook.add_worksheet('TEAM_NAME')
worksheetTN.set_column('A:C', 17)
worksheetTN.set_column('D:D', 50)
for i in range(name_list_num):
    worksheetTN.set_row(i, 30)
# [Note] : virus
"""
建立 TEAM_NAME，即學生與帳號的對應表。
"""
worksheetRT = workbook.add_worksheet('TEAM_ACCOUNT')
worksheetRT.set_column('A:A', 50)
worksheetRT.set_column('B:C', 17)
worksheetRT.set_column('D:D', 50)
for i in range(name_list_num):
    worksheetRT.set_row(i, 30)
# [Note] : virus

# 目前已有幾位同學分配好座位
haveSeat = 0

# 檢查是否應標記為不能使用的座位。
def isInvalidSeat(row, col, invalidSeats):
    for invalidSeat in invalidSeats:
        if row == invalidSeat[0] and col == invalidSeat[1]:
            return True
    return False

"""
建立 328seat 與 328signIn，即 328 教室的座位表與簽到表。
"""
# (1) 定義座位表
seat328 = workbook.add_worksheet('328seat')
seat328.set_column('A:I',17)
seat328.set_column('C:C',2)
seat328.set_column('F:F',2)
seat328.write(0,4,"講台 Front", format5)
seat328.write(8,8,"門 Door", format5)
for i in range(0,9):
    seat328.set_row(i,40)
# (2) 定義簽到表
signIn328 = workbook.add_worksheet('328signIn')
signIn328.set_column('A:I',17)
signIn328.set_column('C:C',2)
signIn328.set_column('F:F',2)
signIn328.write(0,4,"講台 Front", format5)
signIn328.write(8,8,"門 Door", format5)
for i in range(0,9):
    signIn328.set_row(i,40)
# (3) 寫入內容
for row in range(1,9):
    for col in range(0,9):
        if (col == 2 or col == 5) or (row == 8 and col in range(3,9)):
            # 走道/沒有座位
            continue
        elif isInvalidSeat(row, col, seat328_invalid):
            # 不能使用的座位
            seat328.write(row,col," ",format4)
            signIn328.write(row,col," ",format4)
        # [Note] : virus => 跳掉間隔for梅花座
        # elif row % 2 == 0 and col % 3 != 0 and col != 8:    
        #     seat328.write(row,col," ",format2)              
        #     signIn328.write(row,col," ",format2)            
        # elif row % 2 == 1 and col % 3 != 1:                 
        #     seat328.write(row,col," ",format2)              
        #     signIn328.write(row,col," ",format2)       
        # [Note] : virus     
        else:
            if haveSeat < name_list_num and haveSeat < max_seat[0]:
                # 尚未分配完所有同學
                seat328.write(row, col, name_list[haveSeat][1], format3)
                signIn328.write(row, col, "TEAM"+str(account_list[haveSeat][0]), format1)
                worksheetTN.write(haveSeat, 0, name_list[haveSeat][0], format3)
                worksheetTN.write(haveSeat, 1, name_list[haveSeat][1], format3)
                worksheetTN.write(haveSeat, 2, "TEAM"+str(account_list[haveSeat][0]), format3)
                worksheetTN.write(haveSeat, 3, name_list[haveSeat][2], format3)
                # [Note] : virus => 更新加了TEAM_ACCOUNT的sheet
                worksheetRT.write(haveSeat, 0, name_list[haveSeat][2], format3)
                worksheetRT.write(haveSeat, 1, name_list[haveSeat][0], format3)
                worksheetRT.write(haveSeat, 2, name_list[haveSeat][1], format3)
                worksheetRT.write(haveSeat, 3, "TEAM"+str(account_list[haveSeat][0])+"  "+account_list[haveSeat][1], format3)
                # [Note] : virus
                haveSeat += 1
            else:
                # 已經分配完所有同學
                seat328.write(row,col," ",format2)
                signIn328.write(row,col," ",format2)
_328num = haveSeat

"""
建立 326seat 與 326signIn，即 326 教室的座位表與簽到表。
"""
# (1) 定義座位表
seat326 = workbook.add_worksheet('326seat')
seat326.set_column('A:I',18)
for i in range(0,18):
    seat326.set_row(i,40)
seat326.set_row(2,15)
seat326.set_row(5,15)
seat326.set_row(8,15)
seat326.set_row(11,15)
seat326.set_column('D:D',4)
seat326.write(0,4,"講台 Front", format5)
seat326.write(0,7,"門 Door", format5)
# (2) 定義簽到表
signIn326 = workbook.add_worksheet('326signIn')
signIn326.set_column('A:H',18)
for i in range(0,18):
    signIn326.set_row(i,40)
signIn326.set_row(2,15)
signIn326.set_row(5,15)
signIn326.set_row(8,15)
signIn326.set_row(11,15)
signIn326.set_column('D:D',4)
signIn326.write(0,4,"講台 Front", format5)
signIn326.write(0,7,"門 Door", format5)
# (3) 寫入內容
for row in range(1,14):
    for col in range(0,8):
        if (row in [2,5,8,11] and col in [0,1,2,3,4,5,6,7,8]) or (col in [3]):
            # 走道/沒有座位
            continue
        elif isInvalidSeat(row, col, seat326_invalid):
            # 不能使用的座位
            seat326.write(row,col," ",format4)
            signIn326.write(row,col," ",format4)
        # [Note] : virus => 跳掉梅花座for間隔
        # elif row % 3 == 0 and col % 2 != 1:                 
        #     seat326.write(row,col," ",format2)              
        #     signIn326.write(row,col," ",format2)            
        # elif row % 3 == 1 and col % 2 != 0:                 
        #     seat326.write(row,col," ",format2)              
        #     signIn326.write(row,col," ",format2)        
        # [Note] : virus    
        else:
            if haveSeat < name_list_num and haveSeat - _328num < max_seat[1]:
                # 尚未分配完所有同學
                seat326.write(row, col, name_list[haveSeat][1], format3)
                signIn326.write(row, col, "TEAM" + str(account_list[haveSeat][0]), format1)
                worksheetTN.write(haveSeat,0,name_list[haveSeat][0], format3)
                worksheetTN.write(haveSeat,1,name_list[haveSeat][1], format3)
                worksheetTN.write(haveSeat,2,"TEAM"+str(account_list[haveSeat][0]), format3)
                worksheetTN.write(haveSeat,3,name_list[haveSeat][2], format3)
                # [Note] : virus => 更新加了TEAM_ACCOUNT的sheet
                worksheetRT.write(haveSeat, 0, name_list[haveSeat][2], format3)
                worksheetRT.write(haveSeat, 1, name_list[haveSeat][0], format3)
                worksheetRT.write(haveSeat, 2, name_list[haveSeat][1], format3)
                worksheetRT.write(haveSeat, 3, "TEAM"+str(account_list[haveSeat][0])+"  "+account_list[haveSeat][1], format3)
                # [Note] : virus
                haveSeat = haveSeat + 1
            else:
                # 已經分配完所有同學
                seat326.write(row,col," ",format2)
                signIn326.write(row,col," ",format2)
_326num = haveSeat - _328num

"""
建立 323seat 與 323signIn，即 323 教室的座位表與簽到表。
"""
# (1) 定義座位表
seat323 = workbook.add_worksheet('323seat')
seat323.set_column('A:E',17)
seat323.write(0,2,"講台 Front", format5)
seat323.write(0,0,"門 Door", format5)
for i in range(0,9):
    seat323.set_row(i,40)
# (2) 定義簽到表
signIn323 = workbook.add_worksheet('323signIn')
signIn323.set_column('A:E',17)
seat323.write(0,2,"講台 Front", format5)
seat323.write(0,0,"門 Door", format5)
for i in range(0,9):
    signIn323.set_row(i,40)
# (3) 寫入內容
for row in range(1,9):
    for col in range(0,5):
        if (col == 2 or col == 5) or (row == 8 and col in range(3,9)):
            # 走道/沒有座位
            continue
        elif isInvalidSeat(row, col, seat323_invalid):
            # 不能使用的座位
            seat323.write(row,col," ",format4)
            signIn323.write(row,col," ",format4)
        # [Note] : virus => 跳掉間隔for梅花座
        # elif row % 2 == 0 and col % 3 != 0 and col != 8:    
        #     seat328.write(row,col," ",format2)              
        #     signIn328.write(row,col," ",format2)            
        # elif row % 2 == 1 and col % 3 != 1:                 
        #     seat328.write(row,col," ",format2)              
        #     signIn328.write(row,col," ",format2)       
        # [Note] : virus     
        else:
            if haveSeat < name_list_num and haveSeat - _328num - _326num < max_seat[2]:
                # 尚未分配完所有同學
                seat323.write(row, col, name_list[haveSeat][1], format3)
                signIn323.write(row, col, "TEAM"+str(account_list[haveSeat][0]), format1)
                worksheetTN.write(haveSeat, 0, name_list[haveSeat][0], format3)
                worksheetTN.write(haveSeat, 1, name_list[haveSeat][1], format3)
                worksheetTN.write(haveSeat, 2, "TEAM"+str(account_list[haveSeat][0]), format3)
                worksheetTN.write(haveSeat, 3, name_list[haveSeat][2], format3)
                # [Note] : virus => 更新加了TEAM_ACCOUNT的sheet
                worksheetRT.write(haveSeat, 0, name_list[haveSeat][2], format3)
                worksheetRT.write(haveSeat, 1, name_list[haveSeat][0], format3)
                worksheetRT.write(haveSeat, 2, name_list[haveSeat][1], format3)
                worksheetRT.write(haveSeat, 3, "TEAM"+str(account_list[haveSeat][0])+"  "+account_list[haveSeat][1], format3)
                # [Note] : virus
                haveSeat += 1
            else:
                # 已經分配完所有同學
                seat323.write(row,col," ",format2)
                signIn323.write(row,col," ",format2)
_323num = haveSeat - _326num - _328num


print("328:", _328num, "students")
print("326:", _326num, "students")
print("323:", _323num, "students")

columnWidth = 30
elementPerColumn = 15
idx = 0

"""
建立 328_Account，即 328 教室的小紙條。
"""
account328 = workbook.add_worksheet('328_Account')
account328.set_column("A:G",columnWidth)
for i in range(elementPerColumn):
    account328.set_row(i, 25)
row, col = 0, 0
for i in range(_328num):
    if row == elementPerColumn:
        row = 0
        col = col + 1
    account328.write(row, col, "TEAM"+str(account_list[idx][0])+"  "+account_list[idx][1], format2)
    idx = idx + 1
    row = row + 1
account328.write(elementPerColumn-1, col, "328", format2)   # 標示帳密小紙條是哪間的

"""
建立 326_Account，即 326 教室的小紙條。
"""
account326 = workbook.add_worksheet('326_Account')
account326.set_column("A:G",columnWidth)
for i in range(elementPerColumn):
    account326.set_row(i, 25)
row, col = 0, 0
for i in range(_326num):
    if row == elementPerColumn:
        row = 0
        col = col + 1
    account326.write(row, col, "TEAM"+str(account_list[idx][0])+"  "+account_list[idx][1], format2)
    idx = idx + 1
    row = row + 1
account326.write(elementPerColumn-1, col, "326", format2)   # 標示帳密小紙條是哪間的

"""
建立 323_Account，即 323 教室的小紙條。
"""
account323 = workbook.add_worksheet('323_Account')
account323.set_column("A:G",columnWidth)
for i in range(elementPerColumn):
    account323.set_row(i, 25)
row, col = 0, 0
for i in range(_323num):
    if row == elementPerColumn:
        row = 0
        col = col + 1
    account323.write(row, col, "TEAM"+str(account_list[idx][0])+"  "+account_list[idx][1], format2)
    idx = idx + 1
    row = row + 1
account323.write(elementPerColumn-1, col, "323", format2)   # 標示帳密小紙條是哪間的


"""
建立 backup_Account，即 mac (323) 教室的小紙條。
這個分頁還包含備用的小紙條。
"""
backupAccount = workbook.add_worksheet('backup_Account')
backupAccount.set_column("A:G", columnWidth)
for i in range(elementPerColumn):
    backupAccount.set_row(i, 25)
row, col = 0, 0

while idx < len(account_list):
    if row == elementPerColumn:
        row = 0
        col = col + 1
    backupAccount.write(row, col, "TEAM"+str(account_list[idx][0])+"  "+account_list[idx][1], format2)
    idx = idx + 1
    row = row + 1
backupAccount.write(elementPerColumn-1, col, "backup", format2)   # 標示帳密小紙條是哪間的

workbook.close()

# 為328seat, 326seat, macSeat三間教室的座位表，各複製一個sheet 
# 每間教室：一張當作座位表，一張留於簽到時，助教可以拿著核對名字
wb = load_workbook(args.OUTPUT_PATH)

target = wb['328seat']
wb.copy_worksheet(target)
target = wb['326seat']
wb.copy_worksheet(target)
target = wb['323seat']
wb.copy_worksheet(target)

sheets = wb._sheets.copy()
# 複製生成的sheet會在加在excel的最後面，所以做以下步驟移sheet位置
sheets.insert(3, sheets.pop(-3))
sheets.insert(6, sheets.pop(-2))
sheets.insert(9, sheets.pop(-1))
wb._sheets = sheets

wb.save(args.OUTPUT_PATH)

os.system('pause')